<div style="
    background-color: #f2f2f2;
    padding: 15px;
    text-align: center;
">
    <h1 style="
        margin: 0;
        font-family: Arial, sans-serif;
        color: #333;
    ">
        Sentiment Analysis of Amazon Reviews
    </h1>
</div>

# Data Collection & Understanding

In [103]:
# Import libraries

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Load data**

In [55]:
data=pd.read_csv(r"C:\Users\RASHID\Downloads\amazon_review.csv")

In [56]:
data

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A3SBTW3WS4IQSN,B007WTAJTO,NaN,"[0, 0]",No issues.,4.0,Four Stars,1406073600,2014-07-23,138,0,0
1,A18K1ODH1I2MVB,B007WTAJTO,0mie,"[0, 0]","Purchased this for my device, it worked as adv...",5.0,MOAR SPACE!!!,1382659200,2013-10-25,409,0,0
2,A2FII3I2MBMUIA,B007WTAJTO,1K3,"[0, 0]",it works as expected. I should have sprung for...,4.0,nothing to really say....,1356220800,2012-12-23,715,0,0
3,A3H99DFEG68SR,B007WTAJTO,1m2,"[0, 0]",This think has worked out great.Had a diff. br...,5.0,Great buy at this price!!! *** UPDATE,1384992000,2013-11-21,382,0,0
4,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"[0, 0]","Bought it with Retail Packaging, arrived legit...",5.0,best deal around,1373673600,2013-07-13,513,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
4910,A2LBMKXRM5H2W9,B007WTAJTO,"ZM ""J""","[0, 0]",I bought this Sandisk 16GB Class 10 to use wit...,1.0,Do not waste your money.,1374537600,2013-07-23,503,0,0
4911,ALGDLRUI1ZPCS,B007WTAJTO,Zo,"[0, 0]",Used this for extending the capabilities of my...,5.0,Great item!,1377129600,2013-08-22,473,0,0
4912,A2MR1NI0ENW2AD,B007WTAJTO,Z S Liske,"[0, 0]",Great card that is very fast and reliable. It ...,5.0,Fast and reliable memory card,1396224000,2014-03-31,252,0,0
4913,A37E6P3DSO9QJD,B007WTAJTO,Z Taylor,"[0, 0]",Good amount of space for the stuff I want to d...,5.0,Great little card,1379289600,2013-09-16,448,0,0
4914,A8KGFTFQ86IBR,B007WTAJTO,Zza,"[0, 0]",I've heard bad things about this 64gb Micro SD...,5.0,So far so good.,1388620800,2014-02-01,310,0,0

**DATA VISUALIASTION**

In [ ]:
plt.figure(figsize=(6,4))
sns.countplot(x='overall', data=data)
plt.title('Distribution of Ratings')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.show()

In [ ]:
plt.figure(figsize=(8,6))
sns.heatmap(data.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# EDA

In [104]:
# check columns and info

In [58]:
data.columns

Index(['reviewerID', 'asin', 'reviewerName', 'helpful', 'reviewText',
       'overall', 'summary', 'unixReviewTime', 'reviewTime', 'day_diff',
       'helpful_yes', 'total_vote'],
      dtype='object')

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4915 entries, 0 to 4914
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reviewerID      4915 non-null   object
 1   asin            4915 non-null   object
 2   reviewerName    4914 non-null   object
 3   helpful         4915 non-null   object
 4   reviewText      4914 non-null   object
 5   overall         4915 non-null   float64
 6   summary         4915 non-null   object
 7   unixReviewTime  4915 non-null   int64
 8   reviewTime      4915 non-null   object
 9   day_diff        4915 non-null   int64
 10  helpful_yes     4915 non-null   int64
 11  total_vote      4915 non-null   int64
dtypes: float64(1), int64(4), object(7)
memory usage: 460.9+ KB

**DATA PREPROCESSING**

In [64]:
# CHECK MISSING VALUES
data.isna().sum()

reviewerID        0
asin              0
reviewerName      1
helpful           0
reviewText        1
overall           0
summary           0
unixReviewTime    0
reviewTime        0
day_diff          0
helpful_yes       0
total_vote        0
dtype: int64

In [65]:
# Missing value handling

In [66]:
# Replace NaN values in reviewerName with "Unknown"
data['reviewerName'] = data['reviewerName'].fillna('Unknown')

In [67]:
# drop row 
data.dropna(subset=['reviewText'], inplace=True)

In [68]:
data.isna().sum()

reviewerID        0
asin              0
reviewerName      0
helpful           0
reviewText        0
overall           0
summary           0
unixReviewTime    0
reviewTime        0
day_diff          0
helpful_yes       0
total_vote        0
dtype: int64

In [69]:
# DROPING UNWANTED COLUMNS

data.drop(['reviewerID', 'asin', 'reviewerName','helpful','unixReviewTime','reviewTime'],axis=1,inplace=True)

In [70]:
data.columns

Index(['reviewText', 'overall', 'summary', 'day_diff', 'helpful_yes',
       'total_vote'],
      dtype='object')

In [71]:
# Create Sentiment Labels for sentimental analysis
def sentiment_label(rating):
    if rating >= 4:
        return 1
    elif rating == 3:
        return 0
    else:
        return -1

data['sentiment'] = data['overall'].apply(sentiment_label)

In [72]:
data

,reviewText,overall,summary,day_diff,helpful_yes,total_vote,sentiment
0,No issues.,4.0,Four Stars,138,0,0,1
1,"Purchased this for my device, it worked as adv...",5.0,MOAR SPACE!!!,409,0,0,1
2,it works as expected. I should have sprung for...,4.0,nothing to really say....,715,0,0,1
3,This think has worked out great.Had a diff. br...,5.0,Great buy at this price!!! *** UPDATE,382,0,0,1
4,"Bought it with Retail Packaging, arrived legit...",5.0,best deal around,513,0,0,1
...,...,...,...,...,...,...,...
4910,I bought this Sandisk 16GB Class 10 to use wit...,1.0,Do not waste your money.,503,0,0,-1
4911,Used this for extending the capabilities of my...,5.0,Great item!,473,0,0,1
4912,Great card that is very fast and reliable. It ...,5.0,Fast and reliable memory card,252,0,0,1
4913,Good amount of space for the stuff I want to d...,5.0,Great little card,448,0,0,1
4914,I've heard bad things about this 64gb Micro SD...,5.0,So far so good.,310,0,0,1

# Text Preprocessing (Cleaning, Stopwords, Lemmatization)

In [73]:
# 1️⃣ Import required libraries

In [74]:
import string
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\RASHID\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\RASHID\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\RASHID\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [75]:
# 2️⃣ Create preprocessing objects

In [76]:
punctuation = string.punctuation
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [77]:
# 3️⃣ Text cleaning function

In [78]:
def clean(text):
    words = word_tokenize(text.lower())   # lowercase + tokenize
    
    words = [word for word in words 
             if word not in stop_words and word not in punctuation]
    
    words = [lemmatizer.lemmatize(word) for word in words]
    
    return " ".join(words)

In [79]:
# 4️⃣ Apply cleaning to entire dataset

In [80]:
data['clean_review'] = data['reviewText'].apply(clean)

In [81]:
data

,reviewText,overall,summary,day_diff,helpful_yes,total_vote,sentiment,clean_review
0,No issues.,4.0,Four Stars,138,0,0,1,issue
1,"Purchased this for my device, it worked as adv...",5.0,MOAR SPACE!!!,409,0,0,1,purchased device worked advertised never much ...
2,it works as expected. I should have sprung for...,4.0,nothing to really say....,715,0,0,1,work expected sprung higher capacity think mad...
3,This think has worked out great.Had a diff. br...,5.0,Great buy at this price!!! *** UPDATE,382,0,0,1,think worked great.had diff bran 64gb card wen...
4,"Bought it with Retail Packaging, arrived legit...",5.0,best deal around,513,0,0,1,bought retail packaging arrived legit orange e...
...,...,...,...,...,...,...,...,...
4910,I bought this Sandisk 16GB Class 10 to use wit...,1.0,Do not waste your money.,503,0,0,-1,bought sandisk 16gb class 10 use htc inspire 3...
4911,Used this for extending the capabilities of my...,5.0,Great item!,473,0,0,1,used extending capability samsung galaxy note ...
4912,Great card that is very fast and reliable. It ...,5.0,Fast and reliable memory card,252,0,0,1,great card fast reliable come optional adapter...
4913,Good amount of space for the stuff I want to d...,5.0,Great little card,448,0,0,1,good amount space stuff want fit gopro say
4914,I've heard bad things about this 64gb Micro SD...,5.0,So far so good.,310,0,0,1,'ve heard bad thing 64gb micro sd card crappin...

# Feature Extraction (CountVectorizer / TF-IDF)

In [82]:
x=data['clean_review']
x

0                                                   issue
1       purchased device worked advertised never much ...
2       work expected sprung higher capacity think mad...
3       think worked great.had diff bran 64gb card wen...
4       bought retail packaging arrived legit orange e...
                              ...
4910    bought sandisk 16gb class 10 use htc inspire 3...
4911    used extending capability samsung galaxy note ...
4912    great card fast reliable come optional adapter...
4913           good amount space stuff want fit gopro say
4914    've heard bad thing 64gb micro sd card crappin...
Name: clean_review, Length: 4914, dtype: object

In [83]:
y=data['sentiment']
y

0       1
1       1
2       1
3       1
4       1
       ..
4910   -1
4911    1
4912    1
4913    1
4914    1
Name: sentiment, Length: 4914, dtype: int64

In [84]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [85]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

x_train = cv.fit_transform(x_train)
x_test = cv.transform(x_test)

# Model Building

**Logistic Regression**

In [86]:
from sklearn.linear_model import LogisticRegression

In [107]:
lr=LogisticRegression()
lr

lr=lr.fit(x_train,y_train)
y_pred_lr = lr.predict(x_test)

from sklearn.metrics import accuracy_score
acc_lr = accuracy_score(y_test, y_pred_lr)
print("Accuracy:", acc_lr)

**RandomForestClassifier**

In [91]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200)
rf
rf.fit(x_train, y_train)

y_pred_rf= rf.predict(x_test)

In [92]:
acc_rf = accuracy_score(y_test, y_pred_rf)
print("Accuracy:", acc_rf)

Accuracy: 0.9155645981688708

**MultinomialNB**

In [95]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(x_train, y_train)
y_pred_nb = nb.predict(x_test)

In [96]:
acc_nb=accuracy_score(y_test, y_pred_nb)
print("Accuracy:", acc_nb)

Accuracy: 0.9277721261444557

**SVM**

In [97]:
from sklearn.svm import LinearSVC

svm = LinearSVC()
svm.fit(x_train, y_train)
y_pred_svm = svm.predict(x_test)

In [98]:
acc_svm=accuracy_score(y_test, y_pred_svm)
print("Accuracy:", acc_svm)

Accuracy: 0.9328585961342828

# Model Accuracy Comparison

In [108]:
from tabulate import tabulate
table=[['Model','Accuracy score'],['LogisticRegression',acc_lr],['RandomForestClassifier',acc_rf],
       ['MultinomialNB',acc_nb],['svm (LinearSVC)]',acc_svm]]
       
print(tabulate(table,headers='firstrow',tablefmt='fancy_grid'))

╒════════════════════════╤══════════════════╕
│ Model                  │   Accuracy score │
╞════════════════════════╪══════════════════╡
│ LogisticRegression     │         0.93591  │
├────────────────────────┼──────────────────┤
│ RandomForestClassifier │         0.915565 │
├────────────────────────┼──────────────────┤
│ MultinomialNB          │         0.927772 │
├────────────────────────┼──────────────────┤
│ svm (LinearSVC)]       │         0.932859 │
╘════════════════════════╧══════════════════╛

# Prediction

In [100]:
new_review = ["issue"]
# convert using SAME CountVectorizer
new_review_vector = cv.transform(new_review)

# predict using trained Decision Tree
prediction = lr.predict(new_review_vector)

print(prediction)

[1]

In [111]:
review = ["issue"]
review_clean = [clean(review[0])]
review_vec = cv.transform(review_clean)

prediction = lr.predict(review_vec)

if prediction == 1:
    print("Positive Review")
elif prediction == 0:
    print("Neutral Review")
else:
    print("Negative Review")

Positive Review